Fix/revpi 2856/adapt telegrams to serdev
RevolutionPi/linux pull request #145
Opened 2023-03-21 18:53 UTC by linosanfilippo-kunbus

2023-03-28 09:31 UTC, l1k commented
Nit: Commit message of 9752968efb32544ac7156b49452ad7e25a4e9fb7 cites `pibridge_recv_timeout()` instead of `pibridge_req_io()`.

2023-04-03 08:55 UTC, l1k commented on drivers/tty/serdev/pibridge.c
> -		trace_pibridge_receive_timeout(received, len, timeout);
Are you sure that you want to eliminate the tracepoint? I suspect this is erroneous, but if you do want to get rid of the tracepoint, you'd have to update the tracepoint documentation as well.

2023-04-03 08:58 UTC, l1k requested changes
Apart from the two small issues I've commented on, this LGTM.

2023-04-03 16:16 UTC, linosanfilippo-kunbus commented on drivers/tty/serdev/pibridge.c
> -		trace_pibridge_receive_timeout(received, len, timeout);
Right, this tracepoint should stay. I will fix it.

2023-04-04 09:37 UTC, l1k approved these changes

2023-04-04 22:44 UTC, merged