arm(64)/dts/connect4: Reduce SPI frequency of KSZ9897
RevolutionPi/linux pull request #30
Opened 2021-08-04 08:38 UTC by linosanfilippo-kunbus

It turned out that if the SPI frequency for accessing the KSZ9897 is too
high (more than 33MHz) the data read from the PHY registers may be
corrupted if at the same time the USB is accessed. This may be caused by
interferences between the SPI and USB signals.
However reducing the frequency to a value below or equal to 33MHz for the
SPI communication with the switch eliminates this effect.
To be on the save side choose a value of 25MHz.

Signed-off-by: Lino Sanfilippo <l.sanfilippo@kunbus.com>

2021-08-04 09:09 UTC, iluminat23 requested changes

2021-08-04 09:09 UTC, iluminat23 commented on arch/arm/boot/dts/overlays/revpi-connect4-overlay.dts
> +				spi-max-frequency = <25000000>;
Could you add a comment in the file as well?

2021-08-04 09:10 UTC, linosanfilippo-kunbus commented on arch/arm/boot/dts/overlays/revpi-connect4-overlay.dts
> +				spi-max-frequency = <25000000>;
yes, makes sense

2021-08-09 06:29 UTC, iluminat23 approved these changes

2021-08-09 07:58 UTC, merged