dts: revpi-core: add node for revpi core device
RevolutionPi/linux pull request #63
Opened 2022-01-31 13:21 UTC by linosanfilippo-kunbus

Add a new node for a revpi core device. Add a reference to the sniff pin
gpios. This allows the piControl module to retrieve the concerning gpios
without having to know which gpio controller is in use.

Signed-off-by: Lino Sanfilippo <l.sanfilippo@kunbus.com>

2022-02-01 09:05 UTC, iluminat23 requested changes

2022-02-01 09:05 UTC, iluminat23 commented on arch/arm/boot/dts/overlays/revpi-core-overlay.dts
> +			compatible = "kunbus,revpi-core", "brcm,bcm2837",
I think this overwrites the compatible from fragment@0

2022-02-01 09:05 UTC, iluminat23 commented on arch/arm/boot/dts/overlays/revpi-core-overlay.dts
> +	fragment@7 {
Why not adding it to the fragment@0?

2022-02-01 09:05 UTC, iluminat23 commented on arch/arm/boot/dts/overlays/revpi-core-overlay.dts
> +				compatible = "revpi,core";
Would a pibridge based compatible not better?

2022-02-01 09:05 UTC, iluminat23 commented on arch/arm/boot/dts/overlays/revpi-core-overlay.dts
> +				sniff-gpios = <&gpio 42 GPIO_ACTIVE_HIGH>,
Split the gpios in left and right?

2022-02-02 15:11 UTC, l1k commented
FWIW, in 2019 an attempt was made to introduce a serdev driver for the pibridge, which is in part identical to what you're proposing here:

https://github.com/zhan-kunbus/linux/commit/665c7070319f2950249e81e89ec1f19643d7b1ec

The pibridge node was located below the PL011 UART's node. Thereby, the serial core does not instantiate a ttyAMA0 chardev, but instead instantiates a serdev device, to which a pibridge serdev driver binds. The serdev driver implements the request/response protocols spoken on the PiBridge and provides library functions to perform such request/response pairs. Those library function are then used by piControl for the PiBridge communication. As a result, a lot of unmaintainable code in piControl is replaced by a pibridge driver in the kernel. The idea was to add more features to that driver later (such as performing a bus scan using the sniff pins) and eventually upstream it. It would probably not be all that hard to convert your platform_driver to a serdev_device_driver later, if we choose to continue pursuing the initiative that we began in 2019.

2022-02-02 15:16 UTC, l1k commented
We should probably consider amending `Documentation/devicetree/bindings/vendor-prefixes.yaml` with an entry for KUNBUS GmbH.

2022-02-02 18:27 UTC, linosanfilippo-kunbus commented
> FWIW, in 2019 an attempt was made to introduce a serdev driver for the pibridge, which is in part identical to what you're proposing here:
> 
> [zhan-kunbus@665c707](https://github.com/zhan-kunbus/linux/commit/665c7070319f2950249e81e89ec1f19643d7b1ec)
> 
> The pibridge node was located below the PL011 UART's node. Thereby, the serial core does not instantiate a ttyAMA0 chardev, but instead instantiates a serdev device, to which a pibridge serdev driver binds. The serdev driver implements the request/response protocols spoken on the PiBridge and provides library functions to perform such request/response pairs. Those library function are then used by piControl for the PiBridge communication. As a result, a lot of unmaintainable code in piControl is replaced by a pibridge driver in the kernel. The idea was to add more features to that driver later (such as performing a bus scan using the sniff pins) and eventually upstream it. It would probably not be all that hard to convert your platform_driver to a serdev_device_driver later, if we choose to continue pursuing the initiative that we began in 2019.

I like the idea of having the devices like DIO, MIO, etc. as serdevs, but not the piBridge. That should IMHO be represented as a bus at which

2022-02-02 18:58 UTC, l1k commented
Only one serdev device per UART is allowed. The job of the pibridge serdev driver would be to multiplex communication to the devices on the bus (and detect those devices beforehand using the sniff pins). So you'd have a sysfs hierarchy consisting of the UART, the pibridge device below the UART, a bus below the pibridge device, and finally multiple devices on that bus.

I'd model access to the DIO/AIO modules by implementing gpio and iio drivers. However, because communication to the modules (deliberately) happens on a polled/periodic basis, the gpio/iio drivers would use a shadow copy of input/output process data. A user space read is serviced from the shadow copy (instead of performing a live request) and a user space write is serviced by writing to the shadow copy (which will be used upon the next cycle).

We could discuss the architecture in our next tech talk. (And possibly prepone the tech talk so that we have a clear idea before the workshop on Mon/Wed goes down.)

2022-02-03 12:49 UTC, iluminat23 reviewed
With the change in piControl, wouldn't we need this also for Connect?

2022-02-03 13:10 UTC, iluminat23 commented on arch/arm/boot/dts/overlays/revpi-core-overlay.dts
> +	fragment@7 {
As all devices are currently handled separate this is not needed/possible.

2022-02-16 10:50 UTC, l1k reviewed
What is the rationale to use `left` and `right` subnodes` instead of simply having `left-sniff-gpios` and `right-sniff-gpios` properties below the `pibridge` node? The choice to use subnodes seems very unusual and requires an awful lot of additional code. If you had `left-sniff-gpios` and `right-sniff-gpios` properties, you could just retrieve them with `gpiod_get_array()` and be done with it.

2022-02-16 11:04 UTC, linosanfilippo-kunbus commented
Right, we could do without these subnodes. Its a bit a matter of taste I think. The current approach is similar to what we have for LEDs in which each LED is represented by its own node which includes the gpio connected to the LED...

2022-02-16 11:29 UTC, l1k commented
Just looked on my RevPi Core and `leds-gpio` is the *only* driver using such a layout.

2022-02-16 11:30 UTC, l1k commented
I'd definitely prefer `left-sniff-gpios` and `right-sniff-gpios` properties (or something like that) if only because it greatly simplifies the code.

2022-02-16 11:31 UTC, l1k requested changes
_

2022-02-26 09:09 UTC, l1k approved these changes

2022-02-26 09:17 UTC, l1k commented
This GitHub UI is so silly: Merging is blocked despite my approval because @iluminat23 requested changes (which have been addressed) and re-requesting his review doesn't automatically unblock merging. :(

2022-02-28 07:57 UTC, iluminat23 approved these changes

2022-02-28 07:58 UTC, iluminat23 commented
github ...

Done!

2022-02-28 10:12 UTC, merged