Fix/revpi 1836/fix pinctrl
RevolutionPi/linux pull request #72
Opened 2022-02-21 18:36 UTC by linosanfilippo-kunbus

2022-02-23 08:32 UTC, iluminat23 requested changes

2022-02-23 08:32 UTC, iluminat23 commented on arch/arm/boot/dts/overlays/revpi-compact-overlay.dts
> -			eth1_int_pins {
Why don't you add this pinmux to the eth1 node?

2022-02-23 08:32 UTC, iluminat23 commented on arch/arm/boot/dts/overlays/revpi-compact-overlay.dts
> -			ain_mux_pins {
Why don't you add this pinmux to the ain_mux node?

2022-02-23 08:32 UTC, iluminat23 commented on arch/arm/boot/dts/overlays/revpi-compact-overlay.dts
> -			leds_pins {
And the same as above but for the leds node?

2022-02-23 08:32 UTC, iluminat23 commented on arch/arm/boot/dts/overlays/revpi-core-overlay.dts
> -			eth1_2_reset_pins {
The this pin is used by the pb_rst node. So it should reference this pin!

2022-02-23 08:32 UTC, iluminat23 commented on arch/arm/boot/dts/overlays/revpi-flat-overlay.dts
> -			tpm_pins {
The irq pin is used by the tpm node. You should add a reference from there to this pinctrol. The reset is currently unused by the tpm node. If the driver supports a reset gpio we could add it here.

2022-02-23 08:32 UTC, iluminat23 commented on arch/arm/boot/dts/overlays/revpi-flat-overlay.dts
> -				/* irq reset */
The order of the pins in the comment is wrong!
pin 0 is the reset
pin 1 is the irq

2022-02-23 08:32 UTC, iluminat23 commented on arch/arm/boot/dts/overlays/revpi-flat-overlay.dts
> -			mbus_pins {
The mbus node uses pin 21 as interrupt. It should reference this pinctrl

2022-02-23 08:32 UTC, iluminat23 commented on arch/arm/boot/dts/overlays/revpi-flat-overlay.dts
> -			button_pins {
The gpio-keys should reference this pinctrol

2022-02-23 08:32 UTC, iluminat23 commented on arch/arm/boot/dts/overlays/revpi-connect-overlay.dts
> -			eth2_int_pins {
The pileft node should reference this pinctrol

2022-02-23 08:32 UTC, iluminat23 commented on arch/arm/boot/dts/overlays/revpi-connect-overlay.dts
> -			eth2_reset_pins {
The pb_rst node should reference this pinctrl

2022-02-23 08:32 UTC, iluminat23 commented on arch/arm/boot/dts/overlays/revpi-connect-overlay.dts
> -			conbridge_int_pins {
Add this to the pincontroller or move it to https://github.com/RevolutionPi/linux/blob/devel/revpi-5.10/arch/arm/boot/dts/overlays/revpi-con-can-overlay.dts as it is used there.

2022-03-01 11:01 UTC, iluminat23 reviewed
Have checked if there is any difference in behavior with these changes?

2022-03-01 11:02 UTC, iluminat23 approved these changes, later dismissed
Looks good to me

2022-03-01 14:47 UTC, l1k commented
I think by convention, the `compatible` property always comes first. The commits in this pull don't handle that in a uniform manner, e.g. in the Connect overlay, `compatible` precedes the `pinctrl` properties, wheras in the Compact overlay, it's the other way round. The former seems more correct to me. In any case it would be nice to have the same order across all overlays.

2022-03-01 14:49 UTC, l1k requested changes
_

2022-03-01 15:00 UTC, linosanfilippo-kunbus commented
I agree, I will adjust it to have to compatible first everywhere

2022-03-01 15:21 UTC, iluminat23 requested changes
While you are on it could you fix the comment of the tpm_pins irq and reset are reversed.

2022-03-01 15:21 UTC, iluminat23 commented on arch/arm/boot/dts/overlays/revpi-flat-overlay.dts
> -				/* irq reset */
Could you adjust the comment here, while you are on it?

2022-03-01 15:23 UTC, linosanfilippo-kunbus commented
Sure, no prob

2022-03-01 15:30 UTC, iluminat23 approved these changes

2022-03-01 20:35 UTC, l1k approved these changes

2022-03-02 10:50 UTC, merged