serial: amba-pl011: do not time out prematurely when draining tx fifo…
RevolutionPi/linux pull request #94
Opened 2022-04-01 16:21 UTC by linosanfilippo-kunbus

… for rs485

The current timeout for draining the tx fifo is calculated by multiplying
the time it takes to transmit one character (with the given baut rate) with
the maximal number of characters in the tx queue.

This timeout is too short for two reasons:
First when calculating the time to transmit one character integer division
is used which may round down the result in case of a remainder of the
division.

Fix this by rounding up the division result.

Second the hardware may need additional time (e.g for first putting the
characters into the shift registers) before the characters are actually
put onto the wire.

Take this into account by simply doubling the maximum number of iterations
used to wait for the queue drain.

Signed-off-by: Lino Sanfilippo <l.sanfilippo@kunbus.com>

2022-04-02 16:06 UTC, l1k requested changes
In code comment:

s/save/safe/
s/much/many/

2022-04-07 08:55 UTC, iluminat23 reviewed
LGTM, just address the typos @l1k mentioned then it is fine.

2022-04-10 18:22 UTC, l1k approved these changes

2022-04-10 18:23 UTC, l1k commented
https://lore.kernel.org/linux-serial/20220408233503.7251-1-LinoSanfilippo@gmx.de/T/#u

2022-04-11 06:38 UTC, iluminat23 approved these changes

2022-04-11 07:33 UTC, merged